// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Core Version
---
*/
package cmds

import (
	"context"

	"github.com/nexiintra/nexiintra-operations/execution"
	"github.com/nexiintra/nexiintra-operations/utils"
)

func HealthCoreversionPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "nexiintra-operations", "80-health", "20-coreversion.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
