// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Web deploy to production
---
*/
package endpoints

import (
	"context"

	"github.com/nexiintra/nexiintra-operations/execution"
	"github.com/swaggest/usecase"
)

func ProvisionWebdeployproductionPost() usecase.Interactor {
	type Request struct {
		Appname string `query:"appName" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "nexiintra-operations", "60-provision", "10-web.ps1", "", "-appName", input.Appname)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Web deploy to production")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Provision")
	return u
}
